openapi: "3.0.2"
info:
  title: API docs for recruitment task
  version: "1.0"
servers:
  - url: http://localhost
paths:
  /products:
    get:
      responses:
        200:
          description: Product list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /cart/items:
    post:
      summary: Add product to cart (creates order if orderId is not provided)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [ productId, quantity ]
              properties:
                userId:
                  type: integer
                  nullable: true
                orderId:
                  type: integer
                  nullable: true
                productId:
                  type: integer
                quantity:
                  type: integer
      responses:
        200:
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        404:
          description: Product or order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        422:
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /order/{orderId}/promotion/{promotionId}:
    post:
      summary: Apply promotion to order
      parameters:
        - in: path
          name: orderId
          required: true
          schema: { type: integer }
        - in: path
          name: promotionId
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Updated order details
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Order'
  /order/{orderId}:
    get:
      summary: Get order details
      parameters:
        - in: path
          name: orderId
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Order details
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Order'
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
        itemsTotal:
          type: integer
          description: Sum of all items values (including items discounts)
        adjustmentsTotal:
          type: integer
          description: Sum of all additional fees or discounts (discounts are returned as negative values)
        taxTotal:
          type: integer
          nullable: true
          description: Sum of items tax values (if all items are tax-free the value should be null)
        total:
          type: integer
          description: Final price to pay (sum of "itemsTotal" and "adjustmentsTotal")
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'

    OrderItem:
      type: object
      properties:
        id:
          type: integer
        product:
          $ref: '#/components/schemas/Product'
        unitPrice:
          type: integer
          description: Price of a single item
        quantity:
          type: integer
          description: Number of product's items
        discount:
          type: integer
          nullable: true
          description: Percentage discount for item
        discountValue:
          type: integer
          description: Discount value per item from item promotion
        distributedOrderDiscountValue:
          type: integer
          description: Distributed order discount value per item
        discountedUnitPrice:
          type: integer
          description: Price per item after all discounts
        total:
          type: integer
          description: Discounted unit price multiplied by the number of items
        taxValue:
          type: integer
          nullable: true
          description: Amount of tax calculated from "total" and product's tax rate (null if tax-free)

    Product:
      type: object
      description: Details of the product assigned to the item
      properties:
        id:
          type: integer
        code:
          type: string
        name:
          type: string
        type:
          type: string
        price:
          type: integer
        taxRate:
          type: integer
          nullable: true

    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
          required: [ message ]
      required: [ error ]